title:              "The-underdogs"
tagline:            "사수 없는 스타트업 마케터들을 위해"
email:              "jsy1379@gmail.com"
description:        "오늘도 맨땅에 헤딩중인 스타트업 및 소상공인 마케터들을 위해 쉬운말로 설명해주는 디지털마케팅&커리어 기록."
author:             "장성윤"
baseurl:            "/"
url:                "https://the-underdogs.kr"
locale:             "ko_KR"
thumbnail:          "/img/blog_thumb_1200x628.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname

disqus:
  shortname: http-the-underdogs-kr
